spring:
  application:
    name: edge-connect
  profiles:
    # 激活 dev 配置
    active: dev
  mvc:
    # 抛出 404 异常
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edge_connect?user=root&password=root
  web:
    resources:
      # 关闭静态资源映射
      add-mappings: false
  lifecycle:
    # 等待请求结束超时时长
    timeout-per-shutdown-phase: 30s
server:
  # 等待请求结束后再关闭
  shutdown: graceful
edge:
  jwt:
    key: tcVpKhT6zx5XAqDDdjLF23bOd/DDQ1EwSgMuHR/5vig=
