# 该配置文件打开了部分调试日志，用于开发调试
server:
  shutdown: immediate
mybatis-plus:
  configuration:
    # 调试 sql 日志输出
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  config:
    # 导入 .env.yml 配置
    import: optional:file:.env.yml
logging:
  level:
    io:
      # 激活 io.lettuce.core: debug
      lettuce:
        core: debug
    org.springframework.data.redis: debug
