# 该文件为 Edge Connect 的配置文件模板，请不要修改该文件
# 请将该文件复制一份，并使用环境变量激活对应的配置文件
spring:
  application:
    name: edge-connect
  profiles:
    # 激活 dev 配置
    active: dev
  mvc:
    # 抛出 404 异常
    throw-exception-if-no-handler-found: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/edge_connect?user=root&password=root
  mail:
    host: smtp.mail_server.com
    port: 465
    username: mail_user
    password: mail_password
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  web:
    resources:
      # 关闭静态资源映射
      add-mappings: false
  lifecycle:
    # 等待请求结束超时时长
    timeout-per-shutdown-phase: 30s
  redis:
    host: localhost
    port: 6379
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .ftl
    servlet:
      content-type: text/html
server:
  # 等待请求结束后再关闭
  shutdown: graceful
edge:
  jwt:
    key: tcVpKhT6zx5XAqDDdjLF23bOd/DDQ1EwSgMuHR/5vig=
    timeout: 2
  email:
    from: "Edge Connect<admin@edge.com>"
    verify:
      timeout: 10
